FROM node:18-alpine

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY src ./src

COPY tsconfig.json tsconfig.build.json ./

RUN npm run build

COPY .env ./

EXPOSE 3000

CMD ["npm", "run", "start:prod"]